# 해당 workflow의 이름을 정의 합니다. 
name: Node.js 기반 Nextjs & 도커 & AWS 

# 'Events'로 'develop-main'에서 pull request가 발생하면 수행합니다.
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      targetStage:
        description: "배포 환경"
        type: choice
        default: main
        required: true
        options: [main]
    
# Jobs가 수행됩니다.
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
        
# 소스를 체크아웃 받습니다.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=18"
          cache: "pnpm"
          
      - name: Enable and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.11.0 --activate

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build
        run: pnpm build

      - name: Run
        run: pnpm start
